"""
Product Model
Represents products available for custom printing
"""
from sqlalchemy import Column, BigInteger, String, Text, NUMERIC, Boolean, TIMESTAMP, ForeignKey, CheckConstraint
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class Product(Base):
    """Products table"""
    
    __tablename__ = 'products'
    
    # Primary key
    product_id = Column(BigInteger, primary_key=True, autoincrement=True)
    
    # Foreign key
    category_id = Column(BigInteger, ForeignKey('categories.category_id', ondelete='RESTRICT'), nullable=False)
    
    # Product information
    product_name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    base_price = Column(NUMERIC(10, 2), nullable=False)
    
    # Status
    is_active = Column(Boolean, default=True, nullable=False)
    
    # Timestamps
    created_at = Column(TIMESTAMP, server_default=func.current_timestamp())
    updated_at = Column(TIMESTAMP, server_default=func.current_timestamp(), onupdate=func.current_timestamp())
    
    # Foreign keys - tracking who created/updated
    created_by = Column(BigInteger, ForeignKey('admin_users.admin_id', ondelete='SET NULL'), nullable=True)
    updated_by = Column(BigInteger, ForeignKey('admin_users.admin_id', ondelete='SET NULL'), nullable=True)
    
    # Relationships
    category = relationship('Category', back_populates='products')
    product_creator = relationship('AdminUser', foreign_keys=[created_by], back_populates='created_products')
    product_updater = relationship('AdminUser', foreign_keys=[updated_by], back_populates='updated_products')
    
    cart_items = relationship('CartItem', back_populates='product')
    order_items = relationship('OrderItem', back_populates='product')
    
    # Constraints
    __table_args__ = (
        CheckConstraint('base_price >= 0', name='chk_product_base_price'),
    )
    
    def __repr__(self):
        return f"<Product(product_id={self.product_id}, name='{self.product_name}', price={self.base_price})>"
    
    @property
    def price(self):
        """Alias for base_price"""
        return float(self.base_price)
    
    def get_times_ordered(self):
        """Get number of times this product has been ordered"""
        return len(self.order_items)
    
    def get_total_quantity_sold(self):
        """Get total quantity of this product sold"""
        return sum(item.quantity for item in self.order_items)
    
    def get_total_revenue(self):
        """Get total revenue generated by this product"""
        return sum(item.subtotal for item in self.order_items)